### ISSUE TITLE
Wrong episode number being played

### ISSUE THREAD

**Issue by solbu** [Cat5TV/plugin.video.category5#4]
I think I found the problem with playing the wrong episode number.
It is commit 4837df5bd3828804b4cb407bc0b15231d0f1fc24 that introduced the bug.

I found that when reverting that single commit, it behaved as it should and it started playing the correct episode number.

Why that is I have no idea. But my advice would be to revert that change.

**Comment by Cat5TV** [comment]
Cheers solbu. Well spotted. This was already fixed with [this commit](https://github.com/Cat5TV/plugin.video.category5/commit/45dba1c48700117cbcb84d39fb5363be3613f20e). If you're still having trouble please make sure you're running the latest.

The only issue I still see is that you have to exit Kodi if you change the video quality settings and re-open. But everything else seems to be working well.
